variable "proxmox_node" { type = string }
variable "primary_datastore" { type = string }

variable "proxmox_ssh_user" {
  type        = string
  description = "SSH user on the Proxmox node, used by local-exec to curl+unxz the FreeBSD image into the iso datastore"
  default     = "root"
}

variable "proxmox_ssh_host" {
  type        = string
  description = "SSH hostname or IP for the Proxmox node (used by the FreeBSD image download local-exec). Defaults to proxmox_node — override when the node name doesn't resolve from the operator's workstation."
  default     = ""
}

variable "image_datastore" {
  type        = string
  description = "Storage pool for the FreeBSD cloud image download + cloud-init snippets"
  default     = "local"
}

# FreeBSD base image — opnsense-bootstrap turns this into OPNsense on first boot.

variable "freebsd_image_url" {
  type        = string
  description = "FreeBSD 14.3 BASIC-CLOUDINIT qcow2.xz. A local-exec SSHes to the Proxmox node and runs curl | unxz to land the decompressed qcow2 in the iso datastore."
  default     = "https://download.freebsd.org/releases/VM-IMAGES/14.3-RELEASE/amd64/Latest/FreeBSD-14.3-RELEASE-amd64-BASIC-CLOUDINIT-ufs.qcow2.xz"
}

variable "download_freebsd_image" {
  type        = bool
  description = "Have Terraform fetch + decompress the FreeBSD image on the Proxmox node via SSH. Set to false if already uploaded."
  default     = true
}

variable "opnsense_release" {
  type        = string
  description = "OPNsense release the bootstrap script installs, e.g. 26.1"
  default     = "26.1"
}

# VM sizing.

variable "vm_id" {
  type    = number
  default = 200
}

variable "vm_name" {
  type    = string
  default = "opnsense"
}

variable "cpu_cores" {
  type    = number
  default = 2
}
variable "memory_mb" {
  type    = number
  default = 2048
}
variable "disk_size_gb" {
  type    = number
  default = 20
}

# Network.

variable "wan_bridge" {
  type        = string
  description = "Proxmox bridge with a physical uplink; OPNsense WAN gets a DHCP lease here"
}

variable "lan_bridge" {
  type        = string
  description = "Proxmox SDN VNet name — OPNsense LAN attaches here (no uplink)"
}

variable "lan_cidr" {
  type        = string
  description = "CIDR for the Daedalus LAN; OPNsense LAN address = first host"
}

variable "dns_servers" {
  type    = list(string)
  default = ["1.1.1.1", "9.9.9.9"]
}

variable "timezone" {
  type    = string
  default = "America/Chicago"
}

variable "domain_suffix" {
  type    = string
  default = "daedalus.local"
}

# Operator access.

variable "ssh_public_key_path" {
  type        = string
  description = "SSH public key authorized for root on OPNsense"
}

variable "operator_ingress_cidr" {
  type        = string
  description = "Source CIDR allowed to SSH/HTTPS into OPNsense on the WAN interface. Empty disables inbound WAN access (operator must use Crete as a jump host to the LAN side)."
  default     = ""
}

# API key seeding. The OPNsense config.xml embeds the secret as an
# sha512-crypt hash ($6$). Terraform needs the plaintext to configure the
# provider; the hash is generated by the `external` data source below so
# the config.xml ships consistent.

variable "api_key_id" {
  type        = string
  description = "OPNsense API key id (plaintext; 40 chars base64 is typical)"
  sensitive   = true
}

variable "api_key_secret" {
  type        = string
  description = "OPNsense API key secret (plaintext). Hashed via openssl passwd -6 before landing in config.xml."
  sensitive   = true
}

# Firewall rule configuration lands in a follow-up commit once the
# browningluke/opnsense provider schema is validated against a live
# OPNsense. The API key pair is already seeded into config.xml at
# bootstrap so the provider can authenticate the moment it's wired in.
